const Game = require('../../../api/components/game/game.model')

exports.getGroupedStandings = () => {
    return [
        {
            _id: {
                conference: 'afc',
                division: 'north',
            },
            teams: [
                {
                    identifier: 5,
                    city: 'baltimore',
                    name: 'ravens',
                    stadium: 'stadium',
                    rank: 5,
                    win: 14,
                    lost: 2,
                    draw: 0,
                    scored: 320,
                    conceded: 200,
                },
                {
                    identifier: 6,
                    city: 'pittsburgh',
                    name: 'steelers',
                    stadium: 'stadium',
                    rank: 6,
                    win: 9,
                    lost: 7,
                    draw: 0,
                    scored: 300,
                    conceded: 250,
                },
                {
                    identifier: 8,
                    city: 'cleveland',
                    name: 'browns',
                    stadium: 'stadium',
                    rank: 8,
                    win: 7,
                    lost: 9,
                    draw: 0,
                    scored: 200,
                    conceded: 320,
                },
                {
                    identifier: 7,
                    city: 'cincinnati',
                    name: 'bengals',
                    stadium: 'stadium',
                    rank: 7,
                    win: 3,
                    lost: 13,
                    draw: 0,
                    scored: 100,
                    conceded: 420,
                },
            ],
        },
        {
            _id: {
                conference: 'afc',
                division: 'south',
            },
            teams: [
                {
                    identifier: 12,
                    city: 'jacksonville',
                    name: 'jaguars',
                    stadium: 'stadium',
                    rank: 12,
                    win: 12,
                    lost: 4,
                    draw: 0,
                    scored: 320,
                    conceded: 200,
                },
                {
                    identifier: 9,
                    city: 'houston',
                    name: 'texans',
                    stadium: 'stadium',
                    rank: 9,
                    win: 8,
                    lost: 8,
                    draw: 0,
                    scored: 220,
                    conceded: 250,
                },
                {
                    identifier: 10,
                    city: 'tennessee',
                    name: 'titans',
                    stadium: 'stadium',
                    rank: 10,
                    win: 7,
                    lost: 9,
                    draw: 0,
                    scored: 200,
                    conceded: 320,
                },
                {
                    identifier: 11,
                    city: 'indianapolis',
                    name: 'colts',
                    stadium: 'stadium',
                    rank: 11,
                    win: 3,
                    lost: 13,
                    draw: 0,
                    scored: 100,
                    conceded: 420,
                },
            ],
        },
        {
            _id: {
                conference: 'afc',
                division: 'east',
            },
            teams: [
                {
                    identifier: 2,
                    city: 'miami',
                    name: 'dolphins',
                    stadium: 'stadium',
                    rank: 2,
                    win: 11,
                    lost: 5,
                    draw: 0,
                    scored: 320,
                    conceded: 200,
                },
                {
                    identifier: 1,
                    city: 'new england',
                    name: 'patriots',
                    stadium: 'stadium',
                    rank: 1,
                    win: 9,
                    lost: 7,
                    draw: 0,
                    scored: 220,
                    conceded: 250,
                },
                {
                    identifier: 3,
                    city: 'buffalo',
                    name: 'bills',
                    stadium: 'stadium',
                    rank: 3,
                    win: 7,
                    lost: 9,
                    draw: 0,
                    scored: 200,
                    conceded: 320,
                },
                {
                    identifier: 4,
                    city: 'new york',
                    name: 'jets',
                    stadium: 'stadium',
                    rank: 4,
                    win: 3,
                    lost: 13,
                    draw: 0,
                    scored: 100,
                    conceded: 420,
                },
            ],
        },
        {
            _id: {
                conference: 'afc',
                division: 'west',
            },
            teams: [
                {
                    identifier: 14,
                    city: 'oakland',
                    name: 'raiders',
                    stadium: 'stadium',
                    rank: 14,
                    win: 13,
                    lost: 3,
                    draw: 0,
                    scored: 320,
                    conceded: 200,
                },
                {
                    identifier: 13,
                    city: 'kansas city',
                    name: 'chiefs',
                    stadium: 'stadium',
                    rank: 13,
                    win: 9,
                    lost: 7,
                    draw: 0,
                    scored: 280,
                    conceded: 250,
                },
                {
                    identifier: 15,
                    city: 'denver',
                    name: 'broncos',
                    stadium: 'stadium',
                    rank: 15,
                    win: 7,
                    lost: 9,
                    draw: 0,
                    scored: 200,
                    conceded: 320,
                },
                {
                    identifier: 16,
                    city: 'los angeles',
                    name: 'charchers',
                    stadium: 'stadium',
                    rank: 16,
                    win: 3,
                    lost: 13,
                    draw: 0,
                    scored: 100,
                    conceded: 420,
                },
            ],
        },
    ]
}

exports.getWildCardGames = () => {
    return [
        new Game({
            season: 1,
            week: 17,
            homeTeam: {
                rank: 12,
                name: 'jaguars',
                identifier: 12,
                points: 27,
            },
            awayTeam: {
                rank: 13,
                name: 'chiefs',
                identifier: 13,
                points: 30,
            },
        }),
        new Game({
            season: 1,
            week: 17,
            homeTeam: {
                rank: 2,
                name: 'dolphins',
                identifier: 2,
                points: 17,
            },
            awayTeam: {
                rank: 6,
                name: 'steelers',
                identifier: 6,
                points: 30,
            },
        }),
    ]
}

exports.getDivisionalGames = () => {
    return [
        new Game({
            season: 1,
            week: 18,
            homeTeam: {
                rank: 5,
                name: 'ravens',
                identifier: 1,
                points: 17,
            },
            awayTeam: {
                rank: 13,
                name: 'chiefs',
                identifier: 13,
                points: 13,
            },
        }),
        new Game({
            season: 1,
            week: 18,
            homeTeam: {
                rank: 14,
                name: 'raiders',
                identifier: 14,
                points: 17,
            },
            awayTeam: {
                rank: 6,
                name: 'steelers',
                identifier: 6,
                points: 23,
            },
        }),
    ]
}

exports.getChampionshipGames = () => {
    return [
        new Game({
            season: 1,
            week: 19,
            homeTeam: {
                rank: 5,
                name: 'ravens',
                identifier: 5,
                points: 17,
            },
            awayTeam: {
                rank: 6,
                name: 'steelers',
                identifier: 6,
                points: 13,
            },
        }),
        new Game({
            season: 1,
            week: 19,
            homeTeam: {
                rank: 14,
                name: 'raiders',
                identifier: 14,
                points: 17,
            },
            awayTeam: {
                rank: 12,
                name: 'jaguars',
                identifier: 12,
                points: 23,
            },
        }),
    ]
}

exports.getStandings = () => {
    return [
        {
            identifier: 5,
            city: 'baltimore',
            name: 'ravens',
            stadium: 'stadium',
            rank: 5,
            win: 14,
            lost: 2,
            draw: 0,
            scored: 320,
            conceded: 200,
        },
        {
            identifier: 6,
            city: 'pittsburgh',
            name: 'steelers',
            stadium: 'stadium',
            rank: 6,
            win: 9,
            lost: 7,
            draw: 0,
            scored: 300,
            conceded: 250,
        },
        {
            identifier: 8,
            city: 'cleveland',
            name: 'browns',
            stadium: 'stadium',
            rank: 8,
            win: 7,
            lost: 9,
            draw: 0,
            scored: 200,
            conceded: 320,
        },
        {
            identifier: 7,
            city: 'cincinnati',
            name: 'bengals',
            stadium: 'stadium',
            rank: 7,
            win: 3,
            lost: 13,
            draw: 0,
            scored: 100,
            conceded: 420,
        },
        {
            identifier: 12,
            city: 'jacksonville',
            name: 'jaguars',
            stadium: 'stadium',
            rank: 12,
            win: 12,
            lost: 4,
            draw: 0,
            scored: 320,
            conceded: 200,
        },
        {
            identifier: 9,
            city: 'houston',
            name: 'texans',
            stadium: 'stadium',
            rank: 9,
            win: 8,
            lost: 8,
            draw: 0,
            scored: 220,
            conceded: 250,
        },
        {
            identifier: 10,
            city: 'tennessee',
            name: 'titans',
            stadium: 'stadium',
            rank: 10,
            win: 7,
            lost: 9,
            draw: 0,
            scored: 200,
            conceded: 320,
        },
        {
            identifier: 11,
            city: 'indianapolis',
            name: 'colts',
            stadium: 'stadium',
            rank: 11,
            win: 3,
            lost: 13,
            draw: 0,
            scored: 100,
            conceded: 420,
        },
        {
            identifier: 2,
            city: 'miami',
            name: 'dolphins',
            stadium: 'stadium',
            rank: 2,
            win: 11,
            lost: 5,
            draw: 0,
            scored: 320,
            conceded: 200,
        },
        {
            identifier: 1,
            city: 'new england',
            name: 'patriots',
            stadium: 'stadium',
            rank: 1,
            win: 9,
            lost: 7,
            draw: 0,
            scored: 220,
            conceded: 250,
        },
        {
            identifier: 3,
            city: 'buffalo',
            name: 'bills',
            stadium: 'stadium',
            rank: 3,
            win: 7,
            lost: 9,
            draw: 0,
            scored: 200,
            conceded: 320,
        },
        {
            identifier: 4,
            city: 'new york',
            name: 'jets',
            stadium: 'stadium',
            rank: 4,
            win: 3,
            lost: 13,
            draw: 0,
            scored: 100,
            conceded: 420,
        },

        {
            identifier: 14,
            city: 'oakland',
            name: 'raiders',
            stadium: 'stadium',
            rank: 14,
            win: 13,
            lost: 3,
            draw: 0,
            scored: 320,
            conceded: 200,
        },
        {
            identifier: 13,
            city: 'kansas city',
            name: 'chiefs',
            stadium: 'stadium',
            rank: 13,
            win: 9,
            lost: 7,
            draw: 0,
            scored: 280,
            conceded: 250,
        },
        {
            identifier: 15,
            city: 'denver',
            name: 'broncos',
            stadium: 'stadium',
            rank: 15,
            win: 7,
            lost: 9,
            draw: 0,
            scored: 200,
            conceded: 320,
        },
        {
            identifier: 16,
            city: 'los angeles',
            name: 'charchers',
            stadium: 'stadium',
            rank: 16,
            win: 3,
            lost: 13,
            draw: 0,
            scored: 100,
            conceded: 420,
        },
    ]
}
