const Game = require('../../api/components/game/game.model')

const game1 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 1,
        name: 'patriots',
        identifier: 1,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 2,
        name: 'dolphins',
        identifier: 2,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game2 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 3,
        name: 'bills',
        identifier: 3,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 4,
        name: 'jets',
        identifier: 4,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game3 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 5,
        name: 'ravens',
        identifier: 5,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 6,
        name: 'steelers',
        identifier: 6,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game4 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 7,
        name: 'bengals',
        identifier: 7,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 8,
        name: 'browns',
        identifier: 8,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game5 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 9,
        name: 'texans',
        identifier: 9,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 10,
        name: 'titans',
        identifier: 10,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game6 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 11,
        name: 'colts',
        identifier: 11,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 12,
        name: 'jaguars',
        identifier: 12,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game7 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 13,
        name: 'chiefs',
        identifier: 13,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 14,
        name: 'raiders',
        identifier: 14,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game8 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 15,
        name: 'broncos',
        identifier: 15,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 16,
        name: 'chargers',
        identifier: 16,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game9 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 17,
        name: 'cowboys',
        identifier: 17,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 18,
        name: 'giants',
        identifier: 18,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game10 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 19,
        name: 'redskins',
        identifier: 19,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 20,
        name: 'eagles',
        identifier: 20,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game11 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 21,
        name: 'packers',
        identifier: 21,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 22,
        name: 'lions',
        identifier: 22,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game12 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 23,
        name: 'vikings',
        identifier: 23,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 24,
        name: 'bears',
        identifier: 24,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game13 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 25,
        name: 'falcons',
        identifier: 25,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 26,
        name: 'buccaneers',
        identifier: 26,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game14 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 27,
        name: 'panthers',
        identifier: 27,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 28,
        name: 'saints',
        identifier: 28,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game15 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 29,
        name: 'cardinals',
        identifier: 29,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 30,
        name: '49ers',
        identifier: 30,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
const game16 = new Game({
    season: 1,
    week: 16,
    homeTeam: {
        rank: 31,
        name: 'seahawks',
        identifier: 31,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 32,
        name: 'rams',
        identifier: 32,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})

const game17 = new Game({
    season: 1,
    week: 17,
    homeTeam: {
        rank: 1,
        name: 'patriots',
        identifier: 1,
        points: 27,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 3,
        name: 'bills',
        identifier: 3,
        points: 30,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})

const game18 = new Game({
    season: 1,
    week: 17,
    homeTeam: {
        rank: 12,
        name: 'jaguars',
        identifier: 12,
        points: 17,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 14,
        name: 'raiders',
        identifier: 14,
        points: 30,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})

const game19 = new Game({
    season: 1,
    week: 18,
    homeTeam: {
        rank: 5,
        name: 'ravens',
        identifier: 1,
        points: 17,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 13,
        name: 'chiefs',
        identifier: 13,
        points: 13,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})

const game20 = new Game({
    season: 1,
    week: 18,
    homeTeam: {
        rank: 14,
        name: 'raiders',
        identifier: 14,
        points: 17,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 6,
        name: 'steelers',
        identifier: 6,
        points: 23,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})

const game21 = new Game({
    season: 1,
    week: 19,
    homeTeam: {
        rank: 14,
        name: 'raiders',
        identifier: 14,
        points: 17,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 12,
        name: 'jaguars',
        identifier: 12,
        points: 23,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})

const game22 = new Game({
    season: 1,
    week: 19,
    homeTeam: {
        rank: 5,
        name: 'ravens',
        identifier: 5,
        points: 17,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
    awayTeam: {
        rank: 6,
        name: 'steelers',
        identifier: 6,
        points: 13,
        stats: {
            drives: 0,
            punts: 0,
            fieldGoals: 0,
            missedFieldGoals: 0,
            attempts: 0,
            completions: 0,
            yards: 0,
            touchDowns: 0,
            fumble: 0,
            interception: 0,
        },
    },
})
exports.getTestGames = () => {
    return [
        game1,
        game2,
        game3,
        game4,
        game5,
        game6,
        game7,
        game8,
        game9,
        game10,
        game11,
        game12,
        game13,
        game14,
        game15,
        game16,
        game17,
        game18,
        game19,
        game20,
        game21,
        game22,
    ]
}
