const teams = [
    {
        identifier: 1,
        name: 'patriots',
        city: 'new england',
        stadium: 'gillette stadium',
        conference: 'afc',
        division: 'east',
        standings: [
            {
                season: 1,
                rank: 1,
                win: 9,
                lost: 6,
                draw: 0,
                scored: 300,
                conceded: 150,
            },
        ],
    },
    {
        identifier: 2,
        name: 'dolphins',
        city: 'miami',
        stadium: 'hard rock stadium',
        conference: 'afc',
        division: 'east',
        standings: [
            {
                season: 1,
                rank: 2,
                win: 6,
                lost: 9,
                draw: 0,
                scored: 110,
                conceded: 350,
            },
        ],
    },
    {
        identifier: 3,
        name: 'bills',
        city: 'buffalo',
        stadium: 'new era field',
        conference: 'afc',
        division: 'east',
        standings: [
            {
                season: 1,
                rank: 3,
                win: 8,
                lost: 7,
                draw: 0,
                scored: 210,
                conceded: 190,
            },
        ],
    },
    {
        identifier: 4,
        name: 'jets',
        city: 'new york',
        stadium: 'metlife stadium',
        conference: 'afc',
        division: 'east',
        standings: [
            {
                season: 1,
                rank: 4,
                win: 2,
                lost: 13,
                draw: 0,
                scored: 100,
                conceded: 400,
            },
        ],
    },
    {
        identifier: 5,
        name: 'ravens',
        city: 'baltimore',
        stadium: 'm&t bank stadium',
        conference: 'afc',
        division: 'north',
        standings: [
            {
                season: 1,
                rank: 5,
                win: 13,
                lost: 2,
                draw: 0,
                scored: 400,
                conceded: 150,
            },
        ],
    },
    {
        identifier: 6,
        name: 'steelers',
        city: 'pittsburgh',
        stadium: 'heinz field',
        conference: 'afc',
        division: 'north',
        standings: [
            {
                season: 1,
                rank: 6,
                win: 7,
                lost: 8,
                draw: 0,
                scored: 300,
                conceded: 320,
            },
        ],
    },
    {
        identifier: 7,
        name: 'bengals',
        city: 'cincinnati',
        stadium: 'paul brown stadium',
        conference: 'afc',
        division: 'north',
        standings: [
            {
                season: 1,
                rank: 7,
                win: 0,
                lost: 15,
                draw: 0,
                scored: 100,
                conceded: 500,
            },
        ],
    },
    {
        identifier: 8,
        name: 'browns',
        city: 'cleveland',
        stadium: 'firstenergy stadium',
        conference: 'afc',
        division: 'north',
        standings: [
            {
                season: 1,
                rank: 8,
                win: 4,
                lost: 11,
                draw: 0,
                scored: 230,
                conceded: 450,
            },
        ],
    },
    {
        identifier: 9,
        name: 'texans',
        city: 'houston',
        stadium: 'nrg stadium',
        conference: 'afc',
        division: 'south',
        standings: [
            {
                season: 1,
                rank: 9,
                win: 6,
                lost: 8,
                draw: 1,
                scored: 280,
                conceded: 270,
            },
        ],
    },
    {
        identifier: 10,
        name: 'titans',
        city: 'tennessee',
        stadium: 'nissan stadium',
        conference: 'afc',
        division: 'south',
        standings: [
            {
                season: 1,
                rank: 10,
                win: 2,
                lost: 13,
                draw: 0,
                scored: 100,
                conceded: 390,
            },
        ],
    },
    {
        identifier: 11,
        name: 'colts',
        city: 'indianapolis',
        stadium: 'lucas oil stadium',
        conference: 'afc',
        division: 'south',
        standings: [
            {
                season: 1,
                rank: 11,
                win: 7,
                lost: 7,
                draw: 1,
                scored: 270,
                conceded: 250,
            },
        ],
    },
    {
        identifier: 12,
        name: 'jaguars',
        city: 'jacksonville',
        stadium: 'everbank field',
        conference: 'afc',
        division: 'south',
        standings: [
            {
                season: 1,
                rank: 12,
                win: 9,
                lost: 6,
                draw: 0,
                scored: 210,
                conceded: 90,
            },
        ],
    },
    {
        identifier: 13,
        name: 'chiefs',
        city: 'kansas city',
        stadium: 'arrowhead stadium',
        conference: 'afc',
        division: 'west',
        standings: [
            {
                season: 1,
                rank: 13,
                win: 10,
                lost: 5,
                draw: 0,
                scored: 500,
                conceded: 210,
            },
        ],
    },
    {
        identifier: 14,
        name: 'raiders',
        city: 'oakland',
        stadium: 'oakland–alameda county coliseum',
        conference: 'afc',
        division: 'west',
        standings: [
            {
                season: 1,
                rank: 14,
                win: 8,
                lost: 7,
                draw: 0,
                scored: 410,
                conceded: 329,
            },
        ],
    },
    {
        identifier: 15,
        name: 'broncos',
        city: 'denver',
        stadium: 'sports authority field at mile high',
        conference: 'afc',
        division: 'west',
        standings: [
            {
                season: 1,
                rank: 15,
                win: 2,
                lost: 13,
                draw: 0,
                scored: 180,
                conceded: 319,
            },
        ],
    },
    {
        identifier: 16,
        name: 'chargers',
        city: 'los angeles',
        stadium: 'stubhub center',
        conference: 'afc',
        division: 'west',
        standings: [
            {
                season: 1,
                rank: 16,
                win: 0,
                lost: 15,
                draw: 0,
                scored: 80,
                conceded: 420,
            },
        ],
    },
    {
        identifier: 17,
        name: 'cowboys',
        city: 'dallas',
        stadium: 'at&t stadium',
        conference: 'nfc',
        division: 'east',
        standings: [
            {
                season: 1,
                rank: 17,
                win: 0,
                lost: 15,
                draw: 0,
                scored: 80,
                conceded: 420,
            },
        ],
    },
    {
        identifier: 18,
        name: 'giants',
        city: 'new york',
        stadium: 'metlife stadium',
        conference: 'nfc',
        division: 'east',
        standings: [
            {
                season: 1,
                rank: 18,
                win: 2,
                lost: 13,
                draw: 0,
                scored: 180,
                conceded: 319,
            },
        ],
    },
    {
        identifier: 19,
        name: 'redskins',
        city: 'washington',
        stadium: 'fedexfield',
        conference: 'nfc',
        division: 'east',
        standings: [
            {
                season: 1,
                rank: 19,
                win: 8,
                lost: 7,
                draw: 0,
                scored: 410,
                conceded: 329,
            },
        ],
    },
    {
        identifier: 20,
        name: 'eagles',
        city: 'philadelphia',
        stadium: 'lincoln financial field',
        conference: 'nfc',
        division: 'east',
        standings: [
            {
                season: 1,
                rank: 20,
                win: 10,
                lost: 5,
                draw: 0,
                scored: 500,
                conceded: 210,
            },
        ],
    },
    {
        identifier: 21,
        name: 'packers',
        city: 'green bay',
        stadium: 'lambeau field',
        conference: 'nfc',
        division: 'north',
        standings: [
            {
                season: 1,
                rank: 21,
                win: 9,
                lost: 6,
                draw: 0,
                scored: 210,
                conceded: 90,
            },
        ],
    },
    {
        identifier: 22,
        name: 'lions',
        city: 'detroit',
        stadium: 'ford field',
        conference: 'nfc',
        division: 'north',
        standings: [
            {
                season: 1,
                rank: 22,
                win: 7,
                lost: 7,
                draw: 1,
                scored: 270,
                conceded: 250,
            },
        ],
    },
    {
        identifier: 23,
        name: 'vikings',
        city: 'minnesota',
        stadium: 'u.s. bank stadium',
        conference: 'nfc',
        division: 'north',
        standings: [
            {
                season: 1,
                rank: 23,
                win: 2,
                lost: 13,
                draw: 0,
                scored: 100,
                conceded: 390,
            },
        ],
    },
    {
        identifier: 24,
        name: 'bears',
        city: 'chicago',
        stadium: 'soldier field',
        conference: 'nfc',
        division: 'north',
        standings: [
            {
                season: 1,
                rank: 24,
                win: 6,
                lost: 8,
                draw: 1,
                scored: 280,
                conceded: 270,
            },
        ],
    },
    {
        identifier: 25,
        name: 'falcons',
        city: 'atlanta',
        stadium: 'mercedes-benz stadium',
        conference: 'nfc',
        division: 'south',
        standings: [
            {
                season: 1,
                rank: 25,
                win: 4,
                lost: 11,
                draw: 0,
                scored: 230,
                conceded: 450,
            },
        ],
    },
    {
        identifier: 26,
        name: 'buccaneers',
        city: 'tampa bay',
        stadium: 'raymond james stadium',
        conference: 'nfc',
        division: 'south',
        standings: [
            {
                season: 1,
                rank: 26,
                win: 0,
                lost: 15,
                draw: 0,
                scored: 100,
                conceded: 500,
            },
        ],
    },
    {
        identifier: 27,
        name: 'panthers',
        city: 'carolina',
        stadium: 'bank of america stadium',
        conference: 'nfc',
        division: 'south',
        standings: [
            {
                season: 1,
                rank: 27,
                win: 7,
                lost: 8,
                draw: 0,
                scored: 300,
                conceded: 320,
            },
        ],
    },
    {
        identifier: 28,
        name: 'saints',
        city: 'new orleans',
        stadium: 'mercedes-benz superdome',
        conference: 'nfc',
        division: 'south',
        standings: [
            {
                season: 1,
                rank: 28,
                win: 13,
                lost: 2,
                draw: 0,
                scored: 400,
                conceded: 150,
            },
        ],
    },
    {
        identifier: 29,
        name: 'cardinals',
        city: 'arizona',
        stadium: 'university of phoenix stadium',
        conference: 'nfc',
        division: 'west',
        standings: [
            {
                season: 1,
                rank: 29,
                win: 2,
                lost: 13,
                draw: 0,
                scored: 100,
                conceded: 400,
            },
        ],
    },
    {
        identifier: 30,
        name: '49ers',
        city: 'san francisco',
        stadium: 'levis stadium',
        conference: 'nfc',
        division: 'west',
        standings: [
            {
                season: 1,
                rank: 30,
                win: 8,
                lost: 7,
                draw: 0,
                scored: 210,
                conceded: 190,
            },
        ],
    },
    {
        identifier: 31,
        name: 'seahawks',
        city: 'seattle',
        stadium: 'centurylink field',
        conference: 'nfc',
        division: 'west',
        standings: [
            {
                season: 1,
                rank: 31,
                win: 6,
                lost: 9,
                draw: 0,
                scored: 110,
                conceded: 350,
            },
        ],
    },
    {
        identifier: 32,
        name: 'rams',
        city: 'los angeles',
        stadium: 'los angeles memorial coliseum',
        conference: 'nfc',
        division: 'west',
        standings: [
            {
                season: 1,
                rank: 32,
                win: 9,
                lost: 6,
                draw: 0,
                scored: 300,
                conceded: 150,
            },
        ],
    },
]

exports.getTestTeams = () => {
    return teams
}
